[package]
name = "data_structures_and_algorithms"
version = "0.1.0"
authors = "0xIchigo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
